name: tekartik_material_asset
version: 0.3.3
description: Material design assets

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
dev_dependencies:
  test: any
  dev_test:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.10.2+1'