name: tekartik_material_asset
version: 0.3.3
description: Material design assets

environment:
  sdk: ^3.4.0
dependencies:
dev_dependencies:
  test: any
  dev_build:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.2+1'
